//const express = require('express');
import express from 'express';
const router = express.Router();
import controllers from '../controllers/banks.controller.js';
const { bank_list, user_list } = controllers;
// const {bank_list, user_list} = require('../controllers/banks.controller');
router.get('/banks', bank_list);
router.get('/users', user_list);
// module.exports = router;
export default router;